# Generated by Django 4.2 on 2024-07-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted', models.PositiveIntegerField(verbose_name='Обратилось')),
                ('discharged', models.PositiveIntegerField(verbose_name='Выписано')),
                ('operated', models.PositiveIntegerField(verbose_name='Прооперировано')),
                ('born', models.PositiveIntegerField(verbose_name='Родилось')),
            ],
            options={
                'verbose_name': 'Счетчик',
                'verbose_name_plural': 'Счетчик',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Сотрудники', verbose_name='Изображение сотрудника')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО сотрудника')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='ФИО сотрудника')),
                ('name_ky', models.CharField(max_length=50, null=True, verbose_name='ФИО сотрудника')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='ФИО сотрудника')),
                ('position', models.CharField(max_length=50, verbose_name='Должность сотрудника')),
                ('position_ru', models.CharField(max_length=50, null=True, verbose_name='Должность сотрудника')),
                ('position_ky', models.CharField(max_length=50, null=True, verbose_name='Должность сотрудника')),
                ('position_en', models.CharField(max_length=50, null=True, verbose_name='Должность сотрудника')),
                ('category', models.CharField(choices=[('directorate', 'Дирекция'), ('academic_council', 'Ученый совет'), ('employees', 'Сотрудники')], default='employees', max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
