# Generated by Django 4.2 on 2024-07-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('fax', models.CharField(max_length=20, verbose_name='факс номер')),
                ('instagram', models.CharField(max_length=255, verbose_name='Инстаграм')),
                ('facebook', models.CharField(max_length=255, verbose_name='Фейсбук')),
                ('youtube', models.CharField(max_length=255, verbose_name='Ютуб')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
