# Generated by Django 4.2 on 2024-07-05 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Зогловок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Зогловок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Зогловок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Зогловок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('photo_url', models.ImageField(upload_to='blocks/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отделения')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название отделения')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название отделения')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название отделения')),
                ('description', models.TextField(verbose_name='Описание отделения')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание отделения')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание отделения')),
                ('description_en', models.TextField(null=True, verbose_name='Описание отделения')),
                ('photo_url', models.ImageField(upload_to='department/', verbose_name='Фото')),
                ('photo_team', models.ImageField(upload_to='department/', verbose_name='Фото команды')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
    ]
