# Generated by Django 4.2 on 2024-07-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='block',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='block',
            name='description_ru',
        ),
    ]
