# Generated by Django 4.2 on 2024-07-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_remove_block_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='description',
        ),
    ]
