# Generated by Django 4.2 on 2024-07-10 16:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_remove_block_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание отделения'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание отделения'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание отделения'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание отделения'),
        ),
    ]
