# Generated by Django 4.2 on 2024-07-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_alter_department_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='photo_team',
        ),
    ]
